elastic-query-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: test
  password: '{cipher}29ba36bbc80b724ed01dde521166ff851703b11baffa06028ae0fcd8a6f36fdc'
  roles: USER